name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_FROZEN: true

jobs:
  core-unit-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {python-version: '3.11'}
          - {python-version: '3.12'}
          - {python-version: '3.13'}
          - {python-version: '3.14'}

    env:
      COVERAGE_FLAGS: "--cov=fixingahold --cov-report=xml --cov-report=term-missing  --cov-fail-under=90"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.9.5"
          python-version: ${{ matrix.config.python-version }}

      - name: Install Fixing-A-Hole and dependencies
        run: uv sync

      - name: Run python tests
        run: uv run pytest $COVERAGE_FLAGS
